schema {
        query: QueryType
    }


type Specification {
  id: Int
  specification: String
}

type Article {
  id: Int,
  date: String,
  title: String,    
  template: String,
  thumbnail: String,
  slug: String,  
  tags: String,
  cluster: String,
  order: String,
  fileName: String,
  text: String
}

type Tag {
  name: String,
  slug: String
}

type Language {
  name: String
}

type Topic {
  name: String
}

type Project {
  id: Int,
  name: String,
  description: String,
  date: String,
  pushedAt: String,
  createdAt: String,
  hasIssuesEnabled: Boolean,
  homepageUrl: String,
  resourcePath: String,
  openGraphImageUrl: String,
  stargazers: Int,
  forks: Int,
  primaryLanguage: String,
  languages: [Language],
  repositoryTopics: [Topic]
}

type QueryType {
  lastArticlesList: [Article]
  articlesList: [Article]
  tagsList: [Tag]
  articlesListByTag(tag: String) : [Article]  
  getArticleById(id: Int) : Article
  getAllSpecificationTextByArticleSlug(slug: String) : String
  searchArticles(term: String!) : [Article]
  githubProjects: [Project]
}
